### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by gregoryhammond** [nthitz/pluggedTT#1]
I would love to create a bookmarklet that is based on the one you have created, but right now since you have no license on this repo I have to assume that you want to retain full copyright to this.

I would appreciate it if you make this under an open-source license (like some of your other projects) or in the readme mention that the repo is fully copyright of you.

**Comment by nthitz** [comment]
In there now, thanks for the reminder. I'm curious as to what features you are interested in adding. Thanks for your interest

**Comment by gregoryhammond** [comment]
Thanks for putting a license in. I'm going to try and make a [distraction free turntable](https://github.com/gregoryhammond/DistractionFreeTurntableFM), so that someone can be on turntable without having any distractions. 

I have no clue if it will turn out the way I envisage it but the only way to see is to try.
